

---

#mysql

mysql_root_password: root
mysql_databases:
  - name: i3fresh_db
    encoding:  utf8_general_ci
    collation: utf8_general_ci
mysql_users:
  - name: i3fresh
    host: "%"
    password: hserf3i
    priv: "i3fresh_db.*:ALL"
mysql_packages:
  - mariadb-client
  - mariadb-server
  - python-mysqldb



# php
#php_memory_limit: "128M"
#php_max_execution_time: "90"
#php_upload_max_filesize: "256M"
php_packages:
  - php5-cli
  - php5-json
  - php5-common
  - php5-dev
  - php5-gd
  - php5-pdo
  - php5-pecl-apcu
  - php5-xml

