---
- name: update tzdata
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: update sysctl
  command: sysctl -p /etc/sysctl.conf
  
- name: Restart ntp
  service: name=ntp state=restarted

- name: Restart psad
  service: name=psad state=restarted
