# server cleaup ...

---
- name:  Clean Up
  hosts: '{{inventory}}'
  remote_user: root

  tasks:
  - name: Cleaning up
    shell: sudo apt-get -f install && sudo apt-get autoremove && sudo apt-get -y autoclean && sudo apt-get -y clean
