# install php setting

---
- name:  php & composer
  hosts: '{{ inventory }}'
  remote_user: root

  vars_file:
    - vars/main.yml

  roles:
    - { role: geerlingguy.php }
    - { role: geerlingguy.composer }
