# install php setting

---
- name:  php & composer
  hosts: '{{ inventory }}'
  become: yes

 # vars_files:
    #- vars/main.yml

  roles:
    - { role: geerlingguy.php }
    - { role: geerlingguy.composer }
